name: Backend Checks

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  phpcs:
    name: Run Backend Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: 📥 Install PHP dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--classmap-authoritative'

      - name: ✨ PHPCS
        run: composer analyse:phpcs

      - name: 🧐 PHPStan
        run: composer analyse:phpstan
