name: Backend Checks

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

permissions:
  contents: read

jobs:
  backend:
    name: Run Backend Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: '8.1'
          coverage: none

      - name: 📦 Install PHP dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda
        with:
          require-lock-file: true
          composer-options: '--classmap-authoritative'

      - name: 🎨 Check formatting
        run: composer format:check

      - name: 🚨 Lint
        if: success() || failure()
        run: composer lint

      - name: 🔍 Analyse
        if: success() || failure()
        run: composer analyse
