name: Release
on:
  release:
    types: [published]

env:
  HUSKY: 0

permissions:
  contents: read

jobs:
  deploy_to_wp_repository:
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    environment:
      name: wp.org
      url: https://wordpress.org/plugins/${{ vars.PLUGIN_SLUG }}/

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile --prod
      - run: pnpm run build

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        with:
          php-version: '8.1'
          coverage: none

      - name: 📥 Install PHP dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda
        with:
          require-lock-file: true
          composer-options: '--no-dev --ignore-platform-reqs --classmap-authoritative'

      - name: 🚀 WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ vars.PLUGIN_SLUG }}
