name: Plugin asset/readme update
on:
  push:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ vars.PLUGIN_SLUG }}
          IGNORE_OTHER_FILES: true
